# 推荐服务端口配置
server:
  port: 8090

# Spring应用配置
spring:
  application:
    # 应用名称
    name: recommendation-service
  # 数据库连接配置
  datasource:
    # 数据库连接URL
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:nexus}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: ${DB_USER:root}
    # 数据库密码
    password: ${DB_PASSWORD:root}
    # 数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA配置
  jpa:
    hibernate:
      # Hibernate DDL策略
      ddl-auto: update
    # 是否显示SQL语句
    show-sql: true
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQL8Dialect
  # Redis配置
  redis:
    # Redis服务器地址
    host: ${REDIS_HOST:localhost}
    # Redis服务器端口
    port: ${REDIS_PORT:6379}
    # 连接超时时间
    timeout: 2000ms
  # Kafka配置
  kafka:
    # Kafka服务器地址
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    # 生产者配置
    producer:
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # 消费者配置
    consumer:
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 消费者组ID
      group-id: recommendation-service-group
    
# Eureka客户端配置
eureka:
  client:
    service-url:
      # Eureka服务注册中心地址
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
      
# Spring Boot Actuator管理端点配置
management:
  endpoints:
    web:
      exposure:
        # 暴露的端点
        include: health,info