{
 "title": "HTTP Statistics",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).",
 "tags": [
  "spring-boot",
  "micrometer",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Maximum response time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Average response time (with exceptions)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception!=\"None\", uri!~\".*actuator.*\"}[1m]) / rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception!=\"None\", uri!~\".*actuator.*\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}} {{exception}}"
    }
   ]
  },
  {
   "title": "Average response time (without exceptions)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[1m]) / rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  }
 ]
}