# 服务端口配置
server:
  port: 8081

# Spring应用配置
spring:
  application:
    # 应用名称，用于服务注册与发现
    name: user-service
  # 数据库连接配置
  datasource:
    # 数据库连接URL，支持环境变量配置
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:nexus}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: ${DB_USER:root}
    # 数据库密码
    password: ${DB_PASSWORD:root}
    # 数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
  # JPA配置
  jpa:
    hibernate:
      # Hibernate DDL策略：update表示根据实体类自动更新表结构
      ddl-auto: update
    # 是否显示SQL语句
    show-sql: true
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
# Eureka客户端配置
eureka:
  client:
    service-url:
      # Eureka服务注册中心地址
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Seata配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: nexus-tx-group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      nexus-tx-group: default
    grouplist:
      default: nexus-seata:8091
  config:
    type: file
  registry:
    type: eureka
    eureka:
      server-addr: http://nexus-eureka-server:8761/eureka
      weight: 1
      
# Spring Boot Actuator管理端点配置
management:
  endpoints:
    web:
      exposure:
        # 暴露的端点，包括健康检查和基本信息
        include: health,info