# 文件服务端口配置
server:
  port: 8088
  # Tomcat特定配置，用于提高并发处理能力
  tomcat:
    # 最大连接数
    max-connections: 8192
    # 接受队列长度
    accept-count: 1000
    # 最大工作线程数
    max-threads: 400
    # 最小工作线程数
    min-spare-threads: 50

# Spring应用配置
spring:
  application:
    # 应用名称
    name: file-service
  # Servlet多部分文件上传配置
  servlet:
    multipart:
      # 最大文件大小
      max-file-size: 10MB
      # 最大请求大小
      max-request-size: 50MB
    
# Eureka客户端配置
eureka:
  client:
    service-url:
      # Eureka服务注册中心地址
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
      
# MinIO配置
minio:
  # MinIO服务器地址
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  # 访问密钥
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  # 秘密密钥
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  # 默认存储桶名称
  bucket: ${MINIO_BUCKET:nexus-files}
  
# CDN配置
cdn:
  # 是否启用CDN
  enabled: ${CDN_ENABLED:false}
  # CDN域名
  domain: ${CDN_DOMAIN:}
  # CDN协议
  protocol: ${CDN_PROTOCOL:https}
  
# Spring Boot Actuator管理端点配置
management:
  endpoints:
    web:
      exposure:
        # 暴露的端点，包括健康检查、基本信息和Prometheus监控
        include: health,info,prometheus
  # 监控指标配置
  metrics:
    tags:
      application: ${spring.application.name}