groups:
- name: nexus-alerts
  rules:
  # 服务可用性告警
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "服务 {{ $labels.job }} 不可用"
      description: "{{ $labels.instance }} 上的 {{ $labels.job }} 服务已停止运行超过1分钟"

  # 高CPU使用率告警
  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total[1m]) > 0.8
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "服务 {{ $labels.job }} CPU使用率过高"
      description: "{{ $labels.instance }} 上的 {{ $labels.job }} 服务CPU使用率超过80%"

  # 高内存使用率告警
  - alert: HighMemoryUsage
    expr: (jvm_memory_used_bytes / jvm_memory_max_bytes) > 0.85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "服务 {{ $labels.job }} 内存使用率过高"
      description: "{{ $labels.instance }} 上的 {{ $labels.job }} 服务内存使用率超过85%"

  # 高GC频率告警
  - alert: HighGCFrequency
    expr: rate(jvm_gc_pause_seconds_count[5m]) > 10
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "服务 {{ $labels.job }} GC频率过高"
      description: "{{ $labels.instance }} 上的 {{ $labels.job }} 服务每分钟GC次数超过10次"

  # HTTP错误率告警
  - alert: HighHttpErrorRate
    expr: rate(http_server_requests_seconds_count{outcome="SERVER_ERROR"}[5m]) > 0.05
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "服务 {{ $labels.job }} HTTP错误率过高"
      description: "{{ $labels.instance }} 上的 {{ $labels.job }} 服务HTTP 5xx错误率超过5%"

  # 数据库连接池告警
  - alert: HighDatabaseConnectionUsage
    expr: (hikaricp_connections_active / hikaricp_connections_max) > 0.8
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "服务 {{ $labels.job }} 数据库连接池使用率过高"
      description: "{{ $labels.instance }} 上的 {{ $labels.job }} 服务数据库连接池使用率超过80%"

  # Kafka消息积压告警
  - alert: KafkaMessageBacklog
    expr: kafka_consumer_group_lag > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kafka消息积压"
      description: "消费者组 {{ $labels.consumer_group }} 在主题 {{ $labels.topic }} 上的消息积压超过1000条"