global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nexus-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
          'user-service:8081',
          'content-service:8082',
          'message-service:8083',
          'feed-service:8084',
          'group-service:8085',
          'event-service:8086',
          'search-service:8087',
          'file-service:8088',
          'auth-service:8089'
        ]