global:
  scrape_interval: 15s

# 告警规则文件
rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nexus-api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        
  - job_name: 'nexus-user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
      
  - job_name: 'nexus-content-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['content-service:8082']
      
  - job_name: 'nexus-message-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['message-service:8083']
      
  - job_name: 'nexus-feed-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['feed-service:8084']
      
  - job_name: 'nexus-group-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['group-service:8085']
      
  - job_name: 'nexus-event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['event-service:8086']
      
  - job_name: 'nexus-search-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['search-service:8087']
      
  - job_name: 'nexus-file-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['file-service:8088']
      
  - job_name: 'nexus-auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8089']

  # 基础设施监控
  - job_name: 'nexus-mysql'
    static_configs:
      - targets: ['mysql:3306']
    metrics_path: '/metrics'

  - job_name: 'nexus-redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'